name: Sync with GitHub Enterprise
env:
  GITHUB_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}
  GHE_USER: ${{ vars.SYNC_USER }}
  GHE_FULL_USER: ${{ vars.SYNC_USER_NAME }}
  ENTERPRISE_URL: ${{ vars.ENTERPRISE_GIT_URL }}
  ENTERPRISE_EMAIL: ${{ vars.SYNC_USER_EMAIL }}
  DEFAULT_TEMPLATE: ${{ vars.REPO_TEMPLATE }}

on:
  push:
    branches:
      - '*'
      
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check if remote enterprise repo exists
        id: repocheck
        run: git ls-remote https://${{ env.GHE_USER }}:${{ env.GITHUB_TOKEN }}@${{ env.ENTERPRISE_URL }}/${{ github.repository }} -q --exit-code
      - name: Create remote repo
        if: ${{ failure() && steps.repocheck.conclusion == 'failure' }}
        run: |
          echo ${{ env.GITHUB_TOKEN }} > /tmp/token.txt
          gh auth login -p https -h ${{ env.ENTERPRISE_URL }} --with-token < /tmp/token.txt
          gh repo create --public ${{ github.repository }}
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo and all branches to stage
        if: ${{ github.repository != env.DEFAULT_TEMPLATE }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0
      - name: See if dashboard directory exists and create if it doesn't
        id: check_directory
        uses: JJ/files-present-action@releases/v1
        with:
          files: 'dashboard/README.md'
      - name: No Dashboard
        if: ${{ failure() && steps.check_directory.conclusion == 'failure' }}
        run: |
          git config --local user.name ${{ github.actor }}
          git config --local user.email "${{ github.actor}}@users.noreply.github.com"
          mkdir ./dashboard
          echo "README" > ./dashboard/README.md
          git add ./dashboard
          git commit -m "Dashboard directory created!"
#          git remote set-url origin https://${{ env.GHE_USER }}:${{ env.GITHUB_TOKEN }}@${{ env.ENTERPRISE_URL }}/${{ github.repository }}
#          git push
          
#      - name: Push changes  # push the output folder to your repo
#        if: ${{ failure() && steps.check_directory.conclusion == 'failure' }}
#        uses: ad-m/github-push-action@master
##        uses: justjavac/action-gh-push@v1
#        with:
#          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
##          repository: 'https://${{ env.ENTERPRISE_URL }}/${{ github.repository }}'
#          force: true

      - name: Push the repo up to our internal github
#        if: ${{ github.repository != env.DEFAULT_TEMPLATE }}
        if: ${{ failure() && steps.check_directory.conclusion != 'failure' }}
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://${{ env.ENTERPRISE_URL }}/${{ github.repository }}'
          GIT_USERNAME: ${{ env.GHE_USER }}
          GIT_PASSWORD: ${{ env.GITHUB_TOKEN }}
